### ISSUE TITLE
When the user comes back from the browser while on the success page, the files do not open even if the add file button for the CV/Resume field is clicked.

### ISSUE THREAD

**Issue by caginBrew** [BrewInteractive/brew-careers#31]
When the user comes back from the browser while on the success page, the files do not open even if the add file button for the CV/Resume field is clicked.

**Comment by caginBrew** [comment]
CV/Resume alanına sürükle bırak yöntemi ile de dosya eklenemiyor. Eğer sürükle bırak özelliği yok ise bu belirtilmelidir @salihcandusmez

**Comment by salihcandusmez** [comment]
> CV/Resume alanına sürükle bırak yöntemi ile de dosya eklenemiyor. Eğer sürükle bırak özelliği yok ise bu belirtilmelidir @salihcandusmez

böyle bir özelliğimiz yok

**Comment by demirdanis** [comment]
fixed @caginBrew
